export const requests = {
  fetchAllMovies: "/films/all",
  fetchPopularMovies: "/films/popular",
  fetchWatchedMovies: "/films/seen",
  fetchRatedMovies: "/films/rated",
  fetchMovie: "/films/get/",
  fetchSimilarMovies: "/films/similar/",
  fetchLists: "/lists/get/",
  fetchListsWithoutMovies: "/lists/getWithoutMovies/",
  deleteList: "/lists/",
  updateList: "/lists/",
  addList: "/lists/add",
  updateMoviesList: "/lists/update",
  fetchDistinctGenres: "/genres/distinct",
  fetchDistinctProducteurs: "/producers/distinct",
  fecthViewFilmAndUser: "/views/filmAndUser",
  toggleView: "/views/toggle",
  fetchNoteFilmAndUser: "/notes/filmAndUser",
  addNote: "/notes/add",
  fetchSearchAutoCompleteData: "/films/searchAutocomplete",
  fetchRecommandations: "/films/recommandations",
  fetchFilmsGenre: "/films/genre",
  fetchFilmsProducteur: "/films/producteur",
  updateUser: "/auth/update",
};
